spring.application.name=sparkle_ws
server.servlet.context-path=/sparkle_ws
server.port=8081
stripe.secretKey=sk_test_51QqRvN2NF7Xytw99U3Y6ZjuCGNa4h1ng4o5zl09c72Yu2aDERQqbpMhuBegkXZVLnv6UyBNKcfqatbiPraXjGWju009SqFbKYH