# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - sparklePro

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn -f sparkle_ws/pom.xml clean package

      - name: List files after building
        run: ls -R sparkle_ws/target  # Debug step to confirm WAR is created

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: sparkle_ws/target/*.war  # Corrected WAR file path

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: sparkle_ws/target

      - name: List files after downloading artifact
        run: ls -R sparkle_ws/target  # Debug step to confirm WAR is downloaded

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0A29C2B85DCF40C39526B7C961F72D0C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D894F72ED22A47CDA552609B8DC9775C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_00CF8F09F12F4F5493429D9F04F0C0BD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sparklePro'
          slot-name: 'Production'
          package: sparkle_ws/target/*.war  # Corrected WAR file path
